### ISSUE TITLE
Cannot display elasticsearch query

### ISSUE THREAD

**Issue by xadhoom** [mtanda/grafana-histogram-panel#1]
I'm testing this with elasticsearch backend (and grafana master as now) but it does not displays any data.

by inspecting the seriesData variable in module.js@159, my query returns this type of data:

``` javascript
{"target":"docs",
"type":"docs",
"datapoints":[
{"hour_of_day":0,"Max":255},
{"hour_of_day":1,"Max":227},
{"hour_of_day":2,"Max":222},
{"hour_of_day":3,"Max":232},
{"hour_of_day":4,"Max":342},
{"hour_of_day":5,"Max":474},
{"hour_of_day":6,"Max":641},
{"hour_of_day":7,"Max":1010},
{"hour_of_day":8,"Max":1426},
{"hour_of_day":9,"Max":1551},
{"hour_of_day":10,"Max":1532},
{"hour_of_day":11,"Max":1473},
{"hour_of_day":12,"Max":1656},
{"hour_of_day":13,"Max":1966},
{"hour_of_day":14,"Max":1956},
{"hour_of_day":15,"Max":1493},
{"hour_of_day":16,"Max":1688},
{"hour_of_day":17,"Max":1588},
{"hour_of_day":18,"Max":1521},
{"hour_of_day":19,"Max":1508},
{"hour_of_day":20,"Max":1409},
{"hour_of_day":21,"Max":1283},
{"hour_of_day":22,"Max":689},
{"hour_of_day":23,"Max":373}]
}
```

basically, for any timerange, I'm willing to show the distribution across the 24 hours of he day.
The query itself works ok, I'm just struggling to display it :)

any hint?

Also, it is (or will be) possible to show more than one metric as multiple bars on same point of X-axis ?

**Comment by mtanda** [comment]
Sorry, I don't use Elasticsearch with Grafana.
The response format seems to be invalid for current histogram implementation.

Expected format is like following.
![histogram_response](https://cloud.githubusercontent.com/assets/224552/12314525/47925088-bab5-11e5-9fca-d5cfdb8ff30a.png)

> Also, it is (or will be) possible to show more than one metric as multiple bars on same point of X-axis ?

Do you want to stack the graph?
If you want it, it works.
![histogram_stack](https://cloud.githubusercontent.com/assets/224552/12314584/bda43f84-bab5-11e5-855e-049caade73e8.png)

**Comment by xadhoom** [comment]
agreed, I think something must be done also into ES backed, I'll look into it. thanks for now.
