### ISSUE TITLE
Panel stops working 

### ISSUE THREAD

**Issue by aafirvida** [mtanda/grafana-histogram-panel#17]
Hello: 

I'm currently trying to use your panel over grafana 3.1.0 in Ubuntu 16.04 amd64 with google-chrome plugin works some times but must of the time when I click add new Histogram it does nothing at all, url at the top of the browser changes but nothing more. Even when I can create the histogram when I refresh the page it disappears. Any suggestion please ??? this is very important for me. Thanks in advance. Cheers

**Comment by mtanda** [comment]
Not sure, the issue is same as https://github.com/mtanda/grafana-histogram-panel/issues/14#issuecomment-219200051 ?
If so, I try to fix it by this change https://github.com/mtanda/grafana-histogram-panel/pull/16 .
So, would you try to use latest master code?

Thanks,

**Comment by aafirvida** [comment]
Confirme solved in commit 07f3405. Thanks it is working pretty good now

**Comment by mtanda** [comment]
👍 👍
