### ISSUE TITLE
Need help with using histogram plugin..

### ISSUE THREAD

**Issue by nagaprabhanjan** [mtanda/grafana-histogram-panel#18]
Hi,

I am using grafana v3.0.4 and histogram plugin. I am trying to show memory usage of processes in the graph, and surprisingly, for histogram plugin I get the memory size on the x-axis instead of on the y-axis, because of this the graph is expanding and shrinking horizontally. I tried changing various parameters, but in vain. Can anyone please help me show what I am doing wrong here? Attached is a screenshot - each histogram is a process and the processes are spread across based on their memory consumption.
![grafana query](https://cloud.githubusercontent.com/assets/20130054/16343589/9e590a0e-3a55-11e6-8cab-02960affcb5f.png)

**Comment by mtanda** [comment]
Hi,

> for histogram plugin I get the memory size on the x-axis instead of on the y-axis

This is expected behavior of this plugin. This plugin counts each value (e.g. size of memory consumption) occurrences, and plot the number of occurrences on y-axis.

I'm not sure what you want. Do you want plot like heatmaps?
http://www.brendangregg.com/heatmaps.html

**Comment by nagaprabhanjan** [comment]
Hi,

Many thanks for the reply. I want each time series data point as a
histogram which changes its height based on its current value... Something
like an equalizer in an audio player.. How easy will it be to change the
plug in to suite this need?  If you can give some hints, I can take a shot
at it.. Thanks!!

**Comment by mtanda** [comment]
Following the code is main part of this plugin.
https://github.com/mtanda/grafana-histogram-panel/blob/db5e235771e754b1e5a68acf1204621cc738ee80/src/histogram.js#L186-L195

In this plugin, make bucket and count each value occurrence, change these lines will show the graph what you want.
