### ISSUE TITLE
Readme update

### ISSUE THREAD

**Issue by torkelo** [mtanda/grafana-histogram-panel#19]
This panel is listed on grafana.net and we might remove it because the Readme is not currently very good. 

1) Only install instructions (this is already present on grafana.net install tab), so you dont really need these. Could be good to move that to "develop.md"  file 
2) describe how the panel works, any limitations, what data sources you have tested it with.
3) changelog / maybe known issues.

**Comment by mtanda** [comment]
Same as heatmap epoch panel plugin, I'll update README.

**Comment by mtanda** [comment]
I update README, and add CHANGELOG! If these are OK, I increase the version.
