### ISSUE TITLE
Incorrect tooltip value

### ISSUE THREAD

**Issue by hc4** [mtanda/grafana-histogram-panel#21]
In tooltip displayed incorrect value
![image](https://cloud.githubusercontent.com/assets/17475270/16762385/ed6ab2e8-482c-11e6-8958-865e41c87c0d.png)

According to graph, the value under mouse is 25, but in tooltip shows 12.
I am using elastic data source

**Comment by mtanda** [comment]
Thanks for reporting.

I change the original graph panel code little, it might cause the issue.
https://github.com/mtanda/grafana-histogram-panel/pull/10/commits/4a4d8050aac29c7df74cd269f6d05603e54d1a51

**Comment by mtanda** [comment]
To fix this issue, I need to investigate how flot works.
And I don't have enough time to fix this.

**Comment by hc4** [comment]
Found that setting tooltip mode to single fixes the problem.
And in multiple mode it should be fixed in [graph_tooltip.js](https://github.com/grafana/grafana/blob/d95545b5d307e8f48171f4b95f8e6819ba0e3d9f/public/app/plugins/panel/graph/graph_tooltip.js) component.
Currently there is logic, that assumes, that x value is screen coordinate or time.
But in histogramm it is bucket.

**Comment by hc4** [comment]
hm. you have your own tooltip.
And actual problem was in incorrect sorting [here](https://github.com/mtanda/grafana-histogram-panel/blob/master/src/histogram.js#L199)

**Comment by hc4** [comment]
why not use simple for?

```
for(var key in values) {
  result.push([key, values[key]]);
}
```

As I understand dictionary in JS should be sorted by design (at least this is true for Chrome)

**Comment by hc4** [comment]
Also why are you using toFixed [here](https://github.com/mtanda/grafana-histogram-panel/blob/master/src/histogram.js#L192)?
Actual values could be far below 1.

**Comment by mtanda** [comment]
I just take the code from https://github.com/grafana/grafana/pull/949/files, and make panel plugin.
(The PR is closed, but I think it is useful, so I make this plugin.)

**Comment by hc4** [comment]
Ok. I can make PR then to fix tooltip issues

**Comment by mtanda** [comment]
Thanks lot!!

**Comment by mtanda** [comment]
@hc4 I think this issue is caused by mismatching between jquery.flot's bar position and tooltip position calculation.

If you revert this commit, the issue should be resolved.
https://github.com/mtanda/grafana-histogram-panel/pull/10/commits/4a4d8050aac29c7df74cd269f6d05603e54d1a51

The tooltip position calculation code should consider how bar position is changed when bar alignment is "center".

**Comment by hc4** [comment]
I've looked in console.
data array was unsorted, and tooltip logic expects that it sorted,
With my commit it was foxed for Chrome.
So there should be added explicit sorting

**Comment by mtanda** [comment]
I'm not sure what problem you want fix.
I understand the problem is "tooltip value is wrong for x-axis".

wrong:
![wrong](https://cloud.githubusercontent.com/assets/224552/17646105/9853e152-61f5-11e6-9b44-e561b13fffd7.png)
(tooltip should display for "x-axis" 14)

correct:
![correct](https://cloud.githubusercontent.com/assets/224552/17646106/a244f41c-61f5-11e6-9d2b-f99cb923bfd5.png)

**Comment by mtanda** [comment]
And the value seems to be sorted without your change.
![sorted](https://cloud.githubusercontent.com/assets/224552/17646118/13ddb212-61f6-11e6-8766-c97f6d613465.png)

**Comment by mtanda** [comment]
https://github.com/mtanda/grafana-histogram-panel/issues/21#issuecomment-239646390
I understand the value is string, the sort() doesn't work expected.

```
> ["100.1", "10.1", "2.0"].sort()
[ '10.1', '100.1', '2.0' ]
```

**Comment by mtanda** [comment]
I merge PR, but original issue is not resolved.
reopen this issue.

**Comment by hc4** [comment]
I will look again later, but for me tooltip works fine with this fix.

**Comment by hc4** [comment]
I understand.
My problem was, that tooltip displayed same value (10.000, 12) for any bar on graph :)
And this problem was caused by bad sorting.
Second problem, that you shown - tooltip value refreshes only on center of bar.
I will look later how to fix it. Maybe change align, maybe adjust search logic [here](https://github.com/mtanda/grafana-histogram-panel/blob/master/src/histogram_tooltip.js#L25)

**Comment by mtanda** [comment]
Ah, there are two problems!!
I wonder why you think the PR can fix tooltip align problem...
I understand now, you want fix another problem.
If you try to fix center align problem, it's great! 👍 👍 👍
