### ISSUE TITLE
Grafana cli update not working

### ISSUE THREAD

**Issue by urfin78** [mtanda/grafana-histogram-panel#24]
Just tried to update the plugin from grafana-cli tool:

`grafana-cli plugins update grafana-histogram-panel`

and got the following error:

> Error: could not find plugin grafana-histogram-panel in /var/lib/grafana/plugins
> 
> NAME:
>    Grafana cli plugins update - update <plugin id>
> 
> USAGE:
>    Grafana cli plugins update [arguments...]

Seems there is no plugins.js with a plugin id in the plugin folder.

**Comment by mtanda** [comment]
The plugin name "grafana-histogram-panel" is renamed to "mtanda-histogram-panel". (to follow grafana.net plugin naming convention)
You may need to remove past plugin from "/var/lib/grafana/plugins", and reinstall plugin by new plugin name. (sorry for inconvenience.)

**Comment by urfin78** [comment]
Sorry, that was an mistake from me.
I've installed "mtanda-histogram-panel" V.0.1.0 via cli, and I did also an 
`grafana-cli plugins update mtanda-histogram-panel`
but
`grafana-cli plugins ls`
doesn't list the plugin and no "grafana-histogram-panel" either. So I cannot remove it via grafana-cli tool.

**Comment by mtanda** [comment]
You installed both of "grafana-histogram-panel" and "mtanda-histogram-panel"?
Sorry, I'm not sure how the grafana-cli works.
Removing the plugin manually may fix your issue, but not sure it is correct way.

```
sudo rm -rf /var/lib/grafana/plugins/grafana-histogram-panel
```

I only make [plugin.json](https://github.com/mtanda/grafana-histogram-panel/blob/master/src/plugin.json) and register this plugin to grafana.net.

**Comment by urfin78** [comment]
No, I've only installed "mtanda-histogram-panel". The "grafana-histogram-panel" was just a typo in my first post, so there is just a /var/lib/grafana/plugins/mtanda-histogram-panel directory.

**Comment by mtanda** [comment]
Now, I understand what is the problem.

```
% grafana-cli --pluginsDir ~/go/src/github.com/grafana/grafana/data/plugins plugins update mtanda-histogram-panel

Error: could not read find plugin mtanda-histogram-panel

NAME:
   Grafana cli plugins update - update <plugin id>

USAGE:
   Grafana cli plugins update [arguments...]
```

**Comment by mtanda** [comment]
I build latest grafana-cli and test it.

It works. I think this is not a bug of my panel plugin.
Would you try to nightly build Grafana?

```
% bin/grafana-cli --pluginsDir ~/go/src/github.com/grafana/grafana/data/plugins plugins update mtanda-histogram-panel
✔ mtanda-histogram-panel is up to date

Restart grafana after installing plugins . <service grafana-server restart>
```

**Comment by urfin78** [comment]
Ok, after upgrading Grafana from 3.0.4 to 3.1.0 everything works as expected. So this can be closed.
