### ISSUE TITLE
Average calculation in legend

### ISSUE THREAD

**Issue by dstreppa** [mtanda/grafana-histogram-panel#26]
First at all, thank you very much for this plugin @mtanda, it is very useful.
I noticed a problem regarding average calculation in the legend. In my case I should have a voltage value close to 230 V, but Grafana shows me out-of-range and non-sense values (greater than 3000 V). Instead maximum and minimum work fine.

**Comment by dstreppa** [comment]
I think to have found the problem. The average calculation is bound to the bucket size parameter. If I change it, also the average changes.

**Comment by mtanda** [comment]
Thanks for report. I found a bug. I'll fix it.

**Comment by mtanda** [comment]
I fix the bug, I'll register new version to grafana.net.
