### ISSUE TITLE
cannot work with influxdb source

### ISSUE THREAD

**Issue by da-liii** [mtanda/grafana-histogram-panel#30]
<img width="638" alt="2016-08-13 5 22 48" src="https://cloud.githubusercontent.com/assets/1267865/17642460/be395d14-617a-11e6-9bf0-fa2d597a4578.png">

There should be three hists and the y-axis value is not correct.

**Comment by mtanda** [comment]
I'm not sure is this bug, because you don't provide InfluxDB raw response :-<

**Comment by da-liii** [comment]
@mtanda  I figure out what wrong.
It is because the plugin use test.mean as the x-axis value and count of the mean as the y-axis value.

But what I need is that the x-axis should be cpu(a, b or c) and the y-axis should be mean value.

**Comment by mtanda** [comment]
@sadhen Ah, your requirement is similar described in https://github.com/mtanda/grafana-histogram-panel/issues/18.
And it is not supported feature in this histogram plugin...

**Comment by da-liii** [comment]
Thanks @mtanda , #18 helps a lot for me to adapt the code. In your code, the point is (key, key_count). To suit my needs, just change the point to (index, key). Each point has different index thus the columns won't overlap.

**Comment by mtanda** [comment]
Good! I'm not sure how many user want such feature.
If many user want such feature, I'll consider to support it.
