### ISSUE TITLE
cache issue

### ISSUE THREAD

**Issue by steverweber** [mtanda/grafana-histogram-panel#35]
histogram-panel seems to load sometimes but not all the time for some users...

sometimes it gives a "missing plugin error" in place of the histogram.

Im not sure of what the issue is... perhaps cache.

**Comment by steverweber** [comment]
perhaps it's just on mac's browser safari

**Comment by mtanda** [comment]
I try to replicate the issue by using Safari.
I reload dashboard which has histogram panel 10 times, but I can't replicate it.
I cant't imagine the reason, why it can't work, sorry...

**Comment by mtanda** [comment]
I close this issue.
If you still have a issue, please make new issue.
