### ISSUE TITLE
histogram on influxdb

### ISSUE THREAD

**Issue by gtortone** [mtanda/grafana-histogram-panel#39]
Hi,
I'm using Grafana 3.1.1 and InfluxDB 1.0.2;
I'm trying to display an histogram of some temperature values I collect,
but I receive always the error "Cannot read property 'list' of undefined" in the top-left corner
of panel...

**Comment by mtanda** [comment]
Would you share the actual query with me. (by screenshot or something).
I'll check it when I have a time.

**Comment by gtortone** [comment]
Thanks for your response !
In attachment my query; I suppose it is not correct but I did not find any example on how to do it for histograms display....

Thanks again,
Gennaro
![grafana-hist](https://cloud.githubusercontent.com/assets/6534590/19464645/ef0bcf34-9538-11e6-8006-f173926173b8.png)

**Comment by mtanda** [comment]
Sorry for late response.
The issue is very similar with https://github.com/mtanda/grafana-histogram-panel/issues/40 .
If you use Grafana 3.x with histogram panel 0.1.6, please downgrade histogram panel at first.

**Comment by gtortone** [comment]
It works !
Thanks a lot, I just downgraded to 0.1.5 and now it works

**Comment by mtanda** [comment]
Thanks for test!
I specify dependency version, https://github.com/mtanda/grafana-histogram-panel/commit/e06e0c38c58c0700d35a377c7ce13b775fbead97, but it doesn't work.

**Comment by mkeagar** [comment]
Hi @mtanda,

What is the method for downgrading the plugin to 0.1.5? We're having this issue as well. grafana-cli seems to only be able to install the latest version, when I try to specify version via "grafana-cli plugins install mtanda-histogram-plugin @ 0.1.5" I get the error stating it could not find the version I was looking for.

If I just clone your github repository, which branch or commit should I use to get version 0.1.5, as it doesn't appear you have used tags in the repository?

**Comment by mtanda** [comment]
Not sure grafana-cli can specify version.
But if you can use "git clone", you simply checkout following hash. (sorry I didn't tag it)
https://github.com/grafana/grafana-plugin-repository/blob/25e334553f0511c539f0972eac5f9b10bbe6fafe/repo.json#L605
