### ISSUE TITLE
mtanda-histogram-panel 0.1.6 regression using InfluxDB data source

### ISSUE THREAD

**Issue by jerbrownie** [mtanda/grafana-histogram-panel#40]
Panel was previously working with 0.1.5 on influxdb data source, but when installing the latest 0.1.6 histogram panel plugin, javascript error occurs: "Cannot read property 'list' of undefined"

![image](https://cloud.githubusercontent.com/assets/22330243/19492939/92df77fc-952d-11e6-9c4c-47cc02e527b1.png)

Screenshot of it working on system using panel v 0.1.5

![image](https://cloud.githubusercontent.com/assets/22330243/19493036/de4192ca-952d-11e6-9219-8a087d977cec.png)

**Comment by mtanda** [comment]
I may figure out what is the problem.
Do you use Grafana 3.x with histogram-panel 0.1.6?

The version 0.1.6 only work with Grafana 4.x.
If you use Grafana 3.x, please downgrade histogram panel.
