### ISSUE TITLE
toggle histogram series

### ISSUE THREAD

**Issue by gtortone** [mtanda/grafana-histogram-panel#41]
Hi,
with Grafana 3.x it is possible to toggle (enable / disable) a single data series plot clicking on legend row,
but if I do this with histogram it does not work...

it is possible to verify this feature ?

**Comment by mtanda** [comment]
Sorry for late response.
I verify the feature, it works on my env.

Grafana version: 3.1.1-1470047149
histogram panel version: 0.1.5

**Comment by mtanda** [comment]
If the toggle feature still be not working, please open new issue.
