### ISSUE TITLE
data series toggle

### ISSUE THREAD

**Issue by gtortone** [mtanda/grafana-histogram-panel#47]
Hi,
with Grafana 3.x it is possible to toggle (enable / disable) a single data series plot clicking on legend row,
but if I do this with histogram it does not work...

I'm using Grafana 3.1.1 (downloaded from grafana.org)

**Comment by mtanda** [comment]
Hi,
What browser / OS do you use?

**Comment by mtanda** [comment]
If there are some error message, would you share with me?

**Comment by gtortone** [comment]
I verify this problem on these browsers on Linux Ubuntu 14.04.5 (64 bit):
- Firefox 48.0
- Chrome 52.0.2743.116 

no error messages are displayed...

**Comment by gtortone** [comment]
you can verify the problem accessing this Grafana public URL:

http://b2ecl.na.infn.it:7778/dashboard/db/histogram-test

**Comment by mtanda** [comment]
Figure out what is the problem.
The all legend name is "S10B.temperature.mean", it is impossible to toggle legend.
This is original behavior of Grafana normal graph panel. (try to toggle by creating graph panel.)

**Comment by gtortone** [comment]
I just removed mean aggregation function but the result is the same...
you can find new histogram on the previous url

**Comment by mtanda** [comment]
It is strange...
I can toggle the series.
Do I misunderstand what you want?

![histogram_toggle](https://cloud.githubusercontent.com/assets/224552/19800608/6d661286-9d36-11e6-9c34-92d79805b831.png)

**Comment by gtortone** [comment]
Hi, I was working on this...
and now it is fine !

the problem was that I have to define a different name for each measurement (alias in Grafana) in order to toggle single series...

problem solved !

Thanks a lot,
Gennaro

**Comment by mtanda** [comment]
Your welcome 👍
