### ISSUE TITLE
Issue with Crate DB

### ISSUE THREAD

**Issue by mmmatthew** [mtanda/grafana-histogram-panel#48]
I realize that crate isn't listed as a supported database, but since the plugin handles time series, I was hoping that it could handle crate in the same way it handles InfluxDB etc.

Does anyone have experience with crateDB? I am running into errors (see screenshot), and am not sure if they are caused by using Crate.
![image](https://cloud.githubusercontent.com/assets/10126798/19922314/69838c84-a0e2-11e6-9d3e-f5dad4d78188.png)

**Comment by mtanda** [comment]
It might be known issue.
Please downgrade your panel plugin.
https://github.com/mtanda/grafana-histogram-panel/issues/40

**Comment by mmmatthew** [comment]
Thank you. the downgraded panel works fine.
