### ISSUE TITLE
[Graphite]: f.annotations is undefined

### ISSUE THREAD

**Issue by o7g8** [mtanda/grafana-histogram-panel#49]
Hi,

Itrying to get the plugin to work with Graphite and I'm getting following error in my graph (reported with a red small triangle with "!" in the left top corner):

> f.annotations is undefined

The Inspector's panels Request / Response / JS Error are empty.

I don't know if it's related to 
https://github.com/grafana/grafana/issues/841
https://github.com/grafana/grafana/issues/927

**Comment by mtanda** [comment]
I think you may use Grafana 4.0beta.
Please see this https://github.com/mtanda/grafana-histogram-panel/issues/36, and try to use latest panel plugin version.

**Comment by mtanda** [comment]
Sorry, if you still have issue, please reopen.
