### ISSUE TITLE
How to have bucket sizes (which are configured for Histogram in code) in X-Axis and corresponding count of total such occurrences on Y-Axis?

### ISSUE THREAD

**Issue by prasadus92** [mtanda/grafana-histogram-panel#50]
Hey @mtanda , thanks for writing this Plugin. This is obviously a missing very needed feature in Grafana. I have a use case and I am not able to understand how to use this Plugin for that. The use case is given below -

I collect metrics on API HTTP codes. So I would like to have a graph with HTTP Codes on X-Axis and the corresponding number of such occurrences on Y-Axis. May I know whether there is a way to achieve that using this Plugin?

Thanks in advance for your time.

**Comment by mtanda** [comment]
@prasadus92 Sorry for late reply.
This plugin doesn't support such feature.
But, I guess https://github.com/grafana/grafana/pull/5917 is what you want.
Please try it. (you need to use Grafana 4.0 beta version)

**Comment by prasadus92** [comment]
@mtanda No worries, thanks for your response. Yes, this is exactly what I was looking for. Many thanks for your help. Have a great day!
