### ISSUE TITLE
Need query example to show prometheus histogram

### ISSUE THREAD

**Issue by siddontang** [mtanda/grafana-histogram-panel#52]
Hi @mtanda 

Thanks for your great grafana plugin, but I have tried it and don't know how to show my prometheus histogram metric. 

E,g, I have a log_size histogram, with buckets [256, 1024, 4096, 8192], so what I want to show is the same like the example ![](https://raw.githubusercontent.com/mtanda/grafana-histogram-panel/master/dist/images/histogram.png)

x-axis is the bucket and y-axis is the count.

I try to use `sum(log_size) by (le)`, but it doesn't work. Could you give me some advice or an example about the query? 

Thank you very much.

**Comment by mtanda** [comment]
It might be not working.
I'm not sure but Grafana 4.0 feature "non time x-axis" has possibility to support your use case.

**Comment by siddontang** [comment]
Thanks, I will try it.

**Comment by mtanda** [comment]
I'll try the "non time x-axis" mode too :-)

**Comment by robsonpeixoto** [comment]
Do you have any query example, please?
I'm trying something similar to `sum(log_size) by (le)` but is not working

**Comment by larrymeng** [comment]
How to write Query in prometheus data_source?
