### ISSUE TITLE
InfluxDB 1.2.0 issues

### ISSUE THREAD

**Issue by gtortone** [mtanda/grafana-histogram-panel#55]
Hi,
I just upgraded InfluxDB from 1.1.1 to 1.2.0 (released today) with Grafana 4.1.1 and I realized that histograms don't work anymore...

could you reproduce this issue on your side ?

I rolled back to InfluxDB 1.1.1 due to this incompatibility

**Comment by mtanda** [comment]
Hi,
I'll take a look in this weekend

**Comment by mtanda** [comment]
I try to replicate the issue.
Install InfluxDB 1.2.0 by Docker.

```
% curl -sl -I localhost:8086/ping
HTTP/1.1 204 No Content
Content-Type: application/json
Request-Id: 25a3d833-e321-11e6-803d-000000000000
X-Influxdb-Version: 1.2.0
Date: Wed, 25 Jan 2017 17:10:18 GMT
```

And install latest histogram panel (version 0.1.6).
I confirm that it works.
![image](https://cloud.githubusercontent.com/assets/224552/22339469/702e849c-e42d-11e6-8aa5-a8c1cecba7ff.png)

**Comment by mtanda** [comment]
If the panel display error message, please share the error.

**Comment by gtortone** [comment]
Thanks for your support,
I will try to reinstall InfluxDB 1.2.0 and to reproduce the error...

Thanks again !

**Comment by mtanda** [comment]
I close this issue, if you still have a trouble, please open new issue :-)
