### ISSUE TITLE
Histogram config with a prometheus data source

### ISSUE THREAD

**Issue by kelein** [mtanda/grafana-histogram-panel#58]
I had installed histogram plugin by 
```
grafana-cli plugins install mtanda-histogram-panel
```
But I am so confused how to use it with a promethues data source, for example there is a metrics:
```
openstack_allocation_ratio{cloud="openstack",instance="openstack-test:9183",job="openstack_exporter"}
```
How do I config a histogram chart, and how to set a X-axis ? 
Is there any successful example of histogram with prometheus data source ? Thanks.

**Comment by mtanda** [comment]
Sorry, this plugin doesn't support Prometheus `histogram`.
If the metrics is `gauge`, it should work.

**Comment by kelein** [comment]
@mtanda  Meanwhile, I found a [histogram_quantile()](https://prometheus.io/docs/querying/functions/#histogram_quantile()) functions in prometheus official document, I am not sure whether it works with this histogram plugin. 
Refer to [HISTOGRAMS AND SUMMARIES](https://prometheus.io/docs/practices/histograms/).

**Comment by mtanda** [comment]
@Keleir It doesn't return histogram, it return time series value for the specified quantile.
http://demo.robustperception.io:9090/graph?g0.range_input=1h&g0.expr=histogram_quantile(0.9%2C+rate(prometheus_local_storage_series_chunks_persisted_bucket%5B1m%5D))&g0.tab=0

If we can convert `le` label of `histogram` to x-axis, it is possible to draw histogram.
http://demo.robustperception.io:9090/graph?g0.range_input=1h&g0.expr=prometheus_local_storage_series_chunks_persisted_bucket&g0.tab=1
But this plugin doesn't support it.
And Grafana v4 itself histogram panel doesn't support such format too.

I want to stop this plugin development, so I recommend you posting feature request to Grafana.
https://github.com/grafana/grafana/issues/7798 is related issue.
