### ISSUE TITLE
UI suggestions

### ISSUE THREAD

**Issue by jessetan** [mtanda/grafana-histogram-panel#6]
Thanks for taking the time to port the plugin to Grafana 3.0.
There are some issues with the UI that could use some work:
- Axes tab has options to show/hide the x and y axes. I don't think that makes sense for a histogram
- Thresholds don't work in Axes tab
- What should "Avg" in legend show?
- All the draw modes (points, lines, bars) don't do anything, remove?
- Histogram options could be put in Display tab
- Label on x-axis is aligned to left of bar, Would be nice to align with center

**Comment by mtanda** [comment]
Thanks for feedback. (and sorry for late response.)

When I porting changes for Grafana 3.0, I remove some of graph panel feature, it isn't required for histogram, but not all.

> Axes tab has options to show/hide the x and y axes. I don't think that makes sense for a histogram
> All the draw modes (points, lines, bars) don't do anything, remove?

I think these options should be removed too.

> Thresholds don't work in Axes tab

I think this feature is not required for histogram, so I already remove this.

> What should "Avg" in legend show?

I'm not sure, but I don't think it is not fundamental feature for histogram, so I don't have plan to change this.

> Histogram options could be put in Display tab

To reuse Graph panel code, I add Histogram options as new tab.
When I change Display tab options, I'll merge it to Display tab.

> Label on x-axis is aligned to left of bar, Would be nice to align with center

@xadhoom may already fix this issue, I'll check it and if it is fixed, merge the code.
https://github.com/xadhoom/grafana-panel-plugin-histogram/commit/23780fd0394683d38e4bb4fe3437a2a4cf37bb3d

**Comment by mtanda** [comment]
I fix these issues (except Histogram options tab).
