### ISSUE TITLE
With Grafana 4.6.2 adding Histogram plugin to panel does not work

### ISSUE THREAD

**Issue by lasergnu** [mtanda/grafana-histogram-panel#65]
With Grafana 4.6.2 adding Histogram plugin to panel does not work. It says:

    Fetch error: 404 Not Found
    Instantiating http://localhost:3000/public/app/plugins/panel/graph/legend
    Loading http://localhost:3000/public/plugins/mtanda-histogram-panel/histogram_ctrl.js
    Loading plugins/mtanda-histogram-panel/module

**Comment by dsalisbury** [comment]
Looking at the Chrome dev tools, I see this:

![2017-12-14-105952_443x352_scrot](https://user-images.githubusercontent.com/173081/33989037-055f5a04-e0be-11e7-9684-eff03bb9067c.png)

It's trying to get things like `legend.js`, but without the `.js` extension

**Comment by dprime** [comment]
I'm seeing the same issue, sadly.

**Comment by Jeroen88** [comment]
I have the same issue using version 4.6.1
Fetch error: 404 Not Found
Instantiating http://[my domain]/dashboard/public/app/plugins/panel/graph/legend
Loading http://[my domain]/dashboard/public/plugins/mtanda-histogram-panel/histogram_ctrl.js
Loading plugins/mtanda-histogram-panel/module

**Comment by ghost** [comment]
Same here. Latest Grafana.

**Comment by SebastianLavertheDe** [comment]
me too

with Grafana 4.6.2
Plugin Error
Fetch error: 404 Not Found Instantiating http://xxx/public/app/plugins/panel/graph/legend Loading http://xxx/public/plugins/mtanda-histogram-panel/histogram_ctrl.js Loading plugins/mtanda-histogram-panel/module

**Comment by buhtik** [comment]
me too ( The same issue
Grafana: 4.6.3
Plugin: 0.1.6

**Comment by dberzano** [comment]
I have made a little investigation and found out that Grafana has indeed changed something in the plugin system between 4.5.x and 4.6.x. The last working version for Histograms is 4.5.2, the first non-working is 4.6.0.

Have a look at Vonage/Grafana_Status_panel#81 and Vonage/Grafana_Status_panel#82.

**Comment by dberzano** [comment]
(Is this plugin still maintained though?)

**Comment by crholliday** [comment]
Same problem. Anyone find a workaround?

**Comment by dberzano** [comment]
I did. It seems that histograms, since a while (works with 4.5.x and 4.6.x) are now directly supported in the Graph panel. Have a look at this:

![histo](https://user-images.githubusercontent.com/825677/35736512-941a8a20-0828-11e8-8dbb-4fade62ffb1b.jpg)

It's a display option of the X axis now. It seems there is no need for an external plugin for histograms.

**Comment by Jeroen88** [comment]
@dberzano You are right! It is a standard feature now. Thank you very much!

**Comment by artemkozlov752** [comment]
@dberzano  Yes, that's cool! Thank you very much!
