### ISSUE TITLE
Doesn't seem to work with Elasticsearch

### ISSUE THREAD

**Issue by volter** [mtanda/grafana-histogram-panel#8]
Is it supposed to work with Elasticsearch? If so, can you explain what the query should look like?

**Comment by mtanda** [comment]
Sorry, I don't use Elasticsearch. I don't know how to use histogram panel with Elasticsearch.
According to https://github.com/grafana/grafana/issues/3164 issue, @xadhoom success to use with Elasticsearch. You may get hints from the issue.

**Comment by hc4** [comment]
I confirm, that it works with elastic. But you should set aggregation to some value mode (Max, Avg, Min) and specify relatively small time aggregation interval.
![image](https://cloud.githubusercontent.com/assets/17475270/16762256/6a096980-482c-11e6-8b79-8aa31f802450.png)
